version: '3.4'

services:
  shoppingapplicationapinet:
    image: ${DOCKER_REGISTRY-}shoppingapplicationapinet
    build:
      context: .
      dockerfile: ShoppingApplicationAPINET/Dockerfile
    ports:
        - '80:80'
    expose: ['80']